PLANTS = [
    {
        "id": "1",
        "day": "1",
        "date": "January 1st",
        "name": "CHAMOMILE",
        "latin": "Matricaria chamomilla",
        "family": "Asteraceae",
        "origin": "Central Europe & Western Asia",
        "image_local": "static/images/1.jpg",
        "habitat": "Meadows, roadsides, cultivated fields, disturbed soils",
        "figure_legend": "A. Plant, natural size | 1. Flower head with involucre | 2. Flower head — long. section | 3. Ray floret | 4. Disc floret — closed | 5. Disc floret — open | 6. Disc floret — long. section | 7. Stamen tube, style & stigmas | 8. Stigmas of disc floret | 9. Pollen grain | 10. Receptacle | 11. Achene | 12. Achene — cross-section | 13. Achene — long. section",
        "parts_used": "Dried flowers, leaves, stems",
        "harvest": "June – August, in dry weather, at peak bloom",
        "active_compounds": "Chamazulene, Bisabolol, Apigenin, Matricine",
        "properties": "Anti-inflammatory, Antispasmodic, Mild sedative, Carminative, Cicatrizant, Antipyretic",
        "traditional_uses": "Digestive complaints (cramps, bloating, colic, nausea), mild insomnia and anxiety, skin inflammation, eye irritations and conjunctivitis. Used since Antiquity as a fever remedy and nervous system relaxant across European and Middle Eastern traditions.",
        "how_to_use": "Infusion: 1 tsp dried flowers in 250 ml boiling water, steep 5–10 min covered. 2 to 3 cups daily, between meals. | Essential oil: diluted to 2% in a carrier oil (jojoba, sweet almond) for local massage on joint pain or muscle tension. | Compress: a warm chamomile-soaked cloth applied to tired or irritated eyes for 10 minutes. | Tincture: 30 drops in a glass of water, three times a day.",
        "precautions": "Possible allergy in people sensitive to Asteraceae (daisies, ragweed, mugwort). Not recommended in high doses during pregnancy. | Interactions: Anticoagulants (warfarin), sedatives, cyclosporine — consult a healthcare professional.",
        "did_you_know": "In ancient Egypt, chamomile was dedicated to the sun god Ra and used to treat fever. The Anglo-Saxons counted it among their nine sacred herbs, believed to repel poison and disease. In medieval monastery gardens, it was planted between paving stones and called the 'plant of the walker' — the more it was trodden upon, the more it thrived.",
        "location_tags": "Europe · Asia · North Africa · North America (naturalized) · Australia (naturalized)"
    },
    {
        "id": "2",
        "day": "2",
        "date": "January 2nd",
        "name": "PEPPERMINT",
        "latin": "Mentha x piperita",
        "family": "Lamiaceae",
        "origin": "Europe and Middle East",
        "image_local": "static/images/2.jpg",
        "habitat": "Moist soils, riverbanks, damp meadows, cultivated in temperate regions",
        "figure_legend": "A. Flowering branch | 1. Flower head | 2. Calyx opened | 3. Corolla opened showing stamens | 4. Pistil | 5. Nutlets (seeds)",
        "parts_used": "Leaves, flowering tops, essential oil",
        "harvest": "Just before flowering (June-July) for maximum essential oil content",
        "active_compounds": "Menthol, Menthone, Rosmarinic acid, Flavonoids (Luteolin)",
        "properties": "Spasmolytic, Cholagogue, Carminative, Analgesic, Antimicrobial, Antiemetic",
        "traditional_uses": "Relief of irritable bowel syndrome (IBS), dyspepsia, and digestive spasms. Topically used for tension headaches, pruritus, and localized muscle pain relief.",
        "how_to_use": "Infusion: 1 tbsp dried leaves in 150 ml boiling water, steep 10 min. 3 cups daily. | Essential oil: 10% dilution in carrier oil for temples (headache) or abdomen (digestion). | Inhalation: 3 drops in hot water for respiratory congestion.",
        "precautions": "Avoid in patients with gallstones, gastroesophageal reflux (GERD), or severe liver damage. Menthol can cause laryngeal spasms in infants. | Pregnancy: Safe in culinary amounts, consult for therapeutic doses.",
        "did_you_know": "Peppermint is a natural hybrid of watermint (M. aquatica) and spearmint (M. spicata). In Greek mythology, the nymph Menthe was transformed into the plant by Persephone out of jealousy, so that she would be forever trampled underfoot but release a divine scent.",
        "location_tags": "Europe · North America · Asia · Africa (cultivated)"
    },
    {
        "id": "3",
        "day": "3",
        "date": "January 3rd",
        "name": "LEMON BALM",
        "latin": "Melissa officinalis",
        "family": "Lamiaceae",
        "origin": "South Europe and Mediterranean region",
        "image_local": "static/images/3.jpg",
        "habitat": "Forest edges, hedges, gardens, prefers rich and moist soils",
        "figure_legend": "1. Upper part of flowering plant | 2. Flower, side view | 3. Corolla opened | 4. Calyx | 5. Ovary with style | 6. Seed",
        "parts_used": "Leaves (fresh or dried)",
        "harvest": "Before flowering, typically in late spring or early summer",
        "active_compounds": "Rosmarinic acid, Citral, Citronellal, Geraniol",
        "properties": "Anxiolytic, Mild sedative, Spasmolytic, Antiviral (Herpes simplex), Digestive stimulant",
        "traditional_uses": "Treatment of nervous agitation, sleep disorders, and functional gastrointestinal complaints. Historically used as an 'elixir of youth' and for cardiovascular palpitations of nervous origin.",
        "how_to_use": "Infusion: 1.5g to 4g of dried leaves in 150 ml water, steep 10-15 min. Up to 3 times daily. | Topical: Highly concentrated cream (70:1) for cold sores. | Tincture: 2-6 ml, three times daily.",
        "precautions": "May interfere with thyroid hormone replacement therapy. Use with caution in patients with glaucoma. Generally very safe for children and during pregnancy in normal doses.",
        "did_you_know": "The genus name 'Melissa' is Greek for 'honeybee'. The plant has been cultivated for over 2,000 years specifically to attract bees. Paracelsus called it the 'primordial elixir of life', believing it could completely revivify a man.",
        "location_tags": "Central & Southern Europe · Western Asia · North Africa · North America"
    }
]
