PROMPTS = [
    {
        "id": "1",
        "filename": "kappa_river_specimen",
        "prompt": "A biological study of a Kappa, a green reptilian humanoid with a turtle shell on its back and a water-filled dish atop its head, beak-like mouth, webbed hands, squatting posture on a river stone, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 1,
    },
    {
        "id": "2",
        "filename": "tengu_daitengu_profile",
        "prompt": "Anatomical drawing of a Dai-Tengu, a tall winged humanoid with a long prominent red nose and piercing eyes, wearing ascetic mountain monk robes, holding a feather fan, standing in a formal profile view, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 2,
    },
    {
        "id": "3",
        "filename": "tsuchinoko_fat_snake",
        "prompt": "Naturalist illustration of a Tsuchinoko, a thick-bodied short snake with a wide triangular head and mottled scales, depicted in a coiled position as if ready to jump, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 3,
    },
    {
        "id": "4",
        "filename": "kitsune_nine_tails",
        "prompt": "A detailed specimen of a Nine-Tailed Kitsune, a majestic white fox with nine flowing tails tipped with gold, intelligent eyes, depicted in a walking gait showing tail muscle structure, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 4,
    },
    {
        "id": "5",
        "filename": "jorogumo_spider_woman",
        "prompt": "Anatomical study of a Jorogumo, a giant golden orb-weaver spider with the upper torso of a woman emerging from the cephalothorax, intricate web patterns visible, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 5,
    },
    {
        "id": "6",
        "filename": "tanuki_morphology",
        "prompt": "Biological illustration of a Tanuki yokai, a bipedal raccoon dog with a large belly and an oversized scrotum used as a drum, wearing a straw hat and holding a sake flask, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 6,
    },
    {
        "id": "7",
        "filename": "rokurokubi_long_neck",
        "prompt": "Specimen of a Rokurokubi, a woman in a traditional kimono with an unnaturally elongated and serpentine neck, her head drifting far from her shoulders, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 7,
    },
    {
        "id": "8",
        "filename": "gashadokuro_giant_skeleton",
        "prompt": "A scale study of a Gashadokuro, a colossal skeleton made of many human bones, depicted in a crouching pose to fit the frame, showing bone texture and joint connections, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 8,
    },
    {
        "id": "9",
        "filename": "nurikabe_wall_yokai",
        "prompt": "Biological rendering of a Nurikabe, a sentient wall-like creature with a gray stony texture, stubby legs and small eyes, appearing like a rectangular monolith, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 9,
    },
    {
        "id": "10",
        "filename": "ittan_momen_flying_cloth",
        "prompt": "Scientific study of an Ittan-momen, a sentient strip of white cotton cloth with small eyes at one end, depicted twisting through the air in a serpentine motion, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 10,
    },
    {
        "id": "11",
        "filename": "yuki_onna_ice_woman",
        "prompt": "Specimen of Yuki-onna, a tall pale woman with long black hair wearing a white kimono, frost crystals visible on her skin, standing in a serene but cold pose, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 11,
    },
    {
        "id": "12",
        "filename": "karakasa_kozo_umbrella",
        "prompt": "Illustration of a Karakasa-kozo, a sentient oil-paper umbrella with a single large eye, a long tongue, and one leg wearing a wooden geta sandal, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 12,
    },
    {
        "id": "13",
        "filename": "nukekubi_floating_head",
        "prompt": "Anatomical study of a Nukekubi, a severed human head with ghostly trails below the neck, fangs visible in the mouth, floating in mid-air, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 13,
    },
    {
        "id": "14",
        "filename": "umibozu_sea_giant",
        "prompt": "A massive rounded dark head of an Umibozu emerging from waves, smooth black skin with large glowing eyes, atmospheric sea mist, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 14,
    },
    {
        "id": "15",
        "filename": "kamaitachi_sickle_weasel",
        "prompt": "Biological specimen of a Kamaitachi, a lean weasel with sharp sickle-like claws on its paws, captured in a dynamic leaping position, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 15,
    },
    {
        "id": "16",
        "filename": "bakeneko_split_tail",
        "prompt": "Study of a Bakeneko, a large domestic cat with two distinct tails and glowing eyes, standing on its hind legs in a semi-humanoid curiosity, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 16,
    },
    {
        "id": "17",
        "filename": "nurarihyon_old_man",
        "prompt": "Detailed portrait of Nurarihyon, an old man with an elongated gourd-shaped head, wearing expensive silk robes, hands tucked into sleeves, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 17,
    },
    {
        "id": "18",
        "filename": "kodama_tree_spirit",
        "prompt": "Illustration of three Kodama, small pale humanoid tree spirits with asymmetrical heads and hollow black eyes, standing on a gnarled mossy branch, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 18,
    },
    {
        "id": "19",
        "filename": "kirin_mythical_stag",
        "prompt": "Naturalist rendering of a Kirin, a deer-like creature covered in dragon scales with a single horn and a flowing mane of flame, hooves touching the ground lightly, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 19,
    },
    {
        "id": "20",
        "filename": "ohnyamuda_giant_mud",
        "prompt": "Anatomical drawing of an Ohnyamuda, a giant humanoid made of mud and slime with a single large eye, texture of wet clay and earth, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 20,
    },
    {
        "id": "21",
        "filename": "hitotsume_kozo_boy",
        "prompt": "Specimen study of Hitotsume-kozo, a small boy-like monk with a single giant eye in the center of his forehead and a long tongue, wearing a small hat, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 21,
    },
    {
        "id": "22",
        "filename": "onibi_will_o_wisp",
        "prompt": "Biological capture of an Onibi, several floating blue orbs of ghostly fire with faint skeletal faces visible within the flames, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 22,
    },
    {
        "id": "23",
        "filename": "hannya_mask_demon",
        "prompt": "A clinical study of a Hannya demon, a female humanoid with sharp metallic horns, leering metallic teeth, and eyes expressing jealous rage, traditional kimono details, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 23,
    },
    {
        "id": "24",
        "filename": "ushi_oni_cow_spider",
        "prompt": "Morphological study of an Ushi-oni, a monster with the head of a bull and the body of a giant six-legged spider, sharp curved horns and hairy legs, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 24,
    },
    {
        "id": "25",
        "filename": "mokumokuren_eye_shoji",
        "prompt": "Specimen of a Mokumokuren, a section of a traditional shoji sliding paper door with dozens of human eyes peering through the tears in the paper, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 25,
    },
    {
        "id": "26",
        "filename": "namahage_mountain_ogre",
        "prompt": "Full body study of a Namahage, a fierce ogre-like creature in a straw rain-cape, wearing a frightening red mask and carrying a large kitchen knife, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 26,
    },
    {
        "id": "27",
        "filename": "mizuchi_water_dragon",
        "prompt": "Illustration of a Mizuchi, a wingless serpentine water dragon with four legs and small horns, scales reflecting light like wet stones, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 27,
    },
    {
        "id": "28",
        "filename": "nure_onna_snake_woman",
        "prompt": "A biological study of a Nure-onna, a creature with the head of a woman with long wet hair and the body of an enormous giant snake, flicking tongue, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 28,
    },
    {
        "id": "29",
        "filename": "betobeto_san_footsteps",
        "prompt": "A conceptual study of Betobeto-san, an invisible entity represented by a pair of empty floating wooden geta sandals walking on a dark path, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 29,
    },
    {
        "id": "30",
        "filename": "akaname_filth_licker",
        "prompt": "Biological specimen of an Akaname, a small red-skinned humanoid with a long prehensile tongue, depicted in a crouching position with bony limbs, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 30,
    },
    {
        "id": "31",
        "filename": "basan_fire_rooster",
        "prompt": "Naturalist drawing of a Basan, a giant rooster with bright colorful plumage breathing a harmless ghostly blue fire from its beak, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 31,
    },
    {
        "id": "32",
        "filename": "chochin_obake_lantern",
        "prompt": "A specimen of a Chochin-obake, a traditional paper lantern that has grown a large eye and a long tongue, bamboo frame visible through the paper, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 32,
    },
    {
        "id": "33",
        "filename": "daidarabotchi_giant",
        "prompt": "A miniature scale study of a Daidarabotchi, a mountain-sized humanoid whose body is covered in forests and hills, walking slowly across a valley, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 33,
    },
    {
        "id": "34",
        "filename": "furu_utsubo_quiver",
        "prompt": "Illustration of a Furu-utsubo, an ancient archer's quiver that has developed limbs and a face, holding spectral arrows, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 34,
    },
    {
        "id": "35",
        "filename": "futakuchi_onna_two_mouths",
        "prompt": "Anatomical study of a Futakuchi-onna, a woman with a second monstrous mouth located at the back of her head, hidden beneath her long hair, hair strands acting as tentacles, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 35,
    },
    {
        "id": "36",
        "filename": "harionago_hook_hair",
        "prompt": "Specimen of Harionago, a woman with incredibly long hair that ends in sharp, metallic barbs and hooks, hair splayed out in a threatening manner, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 36,
    },
    {
        "id": "37",
        "filename": "hibagon_japanese_bigfoot",
        "prompt": "Cryptid study of the Hibagon, a bipedal ape-like creature with thick black fur, large hands, and a flat face with glowing red eyes, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 37,
    },
    {
        "id": "38",
        "filename": "hyosube_hairy_kappa",
        "prompt": "Biological rendering of a Hyosube, a small, hairy relative of the kappa with balding head and sharp teeth, sitting cross-legged eating eggplants, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 38,
    },
    {
        "id": "39",
        "filename": "inugami_dog_spirit",
        "prompt": "A spectral study of an Inugami, a ghostly dog head with fierce features and sharp fangs, wearing a ceremonial collar, floating in a miasma, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 39,
    },
    {
        "id": "40",
        "filename": "jubokko_vampire_tree",
        "prompt": "Botanical illustration of a Jubokko, a large cedar tree with blood-red sap and branches that look like grasping fingers, surrounded by human remains, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 40,
    },
    {
        "id": "41",
        "filename": "kasha_hell_cat",
        "prompt": "Study of a Kasha, a giant flaming cat demon with two tails, standing on its hind legs amidst embers and smoke, claws extended, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 41,
    },
    {
        "id": "42",
        "filename": "kerakera_onna_laughing",
        "prompt": "Portrait study of Kerakera-onna, a giant cackling woman in a colorful kimono appearing over a wall, face contorted in loud laughter, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 42,
    },
    {
        "id": "43",
        "filename": "kinoko_mushroom_spirit",
        "prompt": "Biological group study of Kinoko, small humanoid spirits with mushroom caps for heads, sitting on a log in a forest setting, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 43,
    },
    {
        "id": "44",
        "filename": "mami_raccoon_badger",
        "prompt": "Illustration of a Mami, a legendary badger-like creature with thick fur and long claws, known for its shapeshifting abilities, shown in its natural form, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 44,
    },
    {
        "id": "45",
        "filename": "ningyo_mermaid_specimen",
        "prompt": "Anatomical specimen of a Japanese Ningyo, a fish-like creature with a human head, sharp teeth, and gold scales, long flowing hair, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 45,
    },
    {
        "id": "46",
        "filename": "noppera_bo_faceless",
        "prompt": "Study of a Noppera-bo, a humanoid figure in a kimono whose face is a completely smooth blank slate with no eyes, nose, or mouth, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 46,
    },
    {
        "id": "47",
        "filename": "nue_chimera_beast",
        "prompt": "Morphological study of a Nue, a chimera with the head of a monkey, the legs of a tiger, the body of a tanuki, and a snake for a tail, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 47,
    },
    {
        "id": "48",
        "filename": "obariyon_piggyback",
        "prompt": "Specimen of an Obariyon, a small heavy humanoid creature that jumps on travelers' backs, with gnarled skin and a heavy burdensome weight, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 48,
    },
    {
        "id": "49",
        "filename": "onyodo_giant_ogre",
        "prompt": "Illustration of an Onyodo, a massive shadowy ogre with blue skin and three eyes, wearing tattered rags and holding a giant club, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 49,
    },
    {
        "id": "50",
        "filename": "osakabe_hime_castle",
        "prompt": "Portrait of Osakabe-hime, a noblewoman yokai who lives in castle lofts, wearing an elaborate multilayered kimono and holding a folding fan, 19th century vintage scientific illustration, biological specimen study, detailed ink and watercolor on aged parchment, anatomical precision, isolated on neutral background, hand-drawn aesthetic, fine stippling and cross-hatching, naturalistic colors, academic botanical style.",
        "seed": 50,
    }
]
