PROMPTS = [
    {
        "id": "1",
        "filename": "kappa_river_photo",
        "prompt": "A real-life Kappa crouching on a slippery river rock, slimy dark green reptilian skin with wet moss patches, a hard turtle shell with serrated edges, the circular indentation on its head filled with shimmering water, sharp beak dripping with river water, webbed claws gripping the stone, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 1,
    },
    {
        "id": "2",
        "filename": "tengu_mountain_perch",
        "prompt": "A massive Daitengu perched on a cedar branch in a misty forest, deep red leathery skin on its long nose, piercing gold bird-like eyes, massive black feathered wings with individual iridescent quills visible, wearing tattered traditional ascetic robes, sharp talons gripping wood, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 2,
    },
    {
        "id": "3",
        "filename": "tsuchinoko_grass_macro",
        "prompt": "A Tsuchinoko snake hidden in tall dry grass, extremely thick and bloated body with mottled brown and copper scales, a wide triangular viper-like head with vertical slit pupils, flickering forked tongue, heavy muscular tail, macro wildlife shot, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 3,
    },
    {
        "id": "4",
        "filename": "kitsune_white_forest",
        "prompt": "A wild white fox with nine distinct, heavy furred tails fanned out behind it, intelligent amber eyes, glowing ethereal whiskers, standing in a sun-dappled ancient forest, individual hairs visible in the thick winter coat, paws stepping on damp leaves, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 4,
    },
    {
        "id": "5",
        "filename": "jorogumo_dark_web",
        "prompt": "A terrifying Jorogumo in the center of a massive sticky web, the creature has the thick hairy legs of a giant orb-weaver spider and the pale torso of a woman with jet black hair, chitinous plates merging with skin, multiple black eyes reflecting light, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 5,
    },
    {
        "id": "6",
        "filename": "tanuki_wild_bipedal",
        "prompt": "A wild Tanuki standing on its hind legs in a bamboo grove, thick coarse fur with black mask markings around the eyes, oversized belly, clutching a stolen ceramic flask, bushy tail, wet nose, realistic animal anatomy mixed with supernatural proportions, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 6,
    },
    {
        "id": "7",
        "filename": "rokurokubi_interior_night",
        "prompt": "A woman in a dark house, her neck unnaturally extended by three meters, twisting like a serpent towards a cracked window, realistic skin stretching with visible tendons and veins, traditional kimono texture, flickering candle lighting, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 7,
    },
    {
        "id": "8",
        "filename": "gashadokuro_night_field",
        "prompt": "A colossal skeleton Gashadokuro looming over a dark rice field, giant weathered yellow bones with cracks and soil stains, pinpoints of white light in huge empty eye sockets, cinematic low angle shot making it look 15 meters tall, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 8,
    },
    {
        "id": "9",
        "filename": "nurikabe_misty_path",
        "prompt": "A Nurikabe blocking a narrow mountain trail at dusk, appearing as a massive slab of living lichen-covered granite, two tiny glowing eyes embedded in the rock-like flesh, moss and dirt at its base, heavy monolithic presence, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 9,
    },
    {
        "id": "10",
        "filename": "ittan_momen_aerial",
        "prompt": "An Ittan-momen flying through a moonlit sky, a long strip of coarse sentient white cotton, weave of the fabric visible, two dark ocular slits, twisting like a snake in the wind, blurred forest canopy below, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 10,
    },
    {
        "id": "11",
        "filename": "yuki_onna_snowstorm",
        "prompt": "Yuki-onna standing in a heavy blizzard, skin as white as blue-tinted ice, long black hair matted with snowflakes, violet eyes, wearing a thin white kimono that blends into the snow, frost on eyelashes, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 11,
    },
    {
        "id": "12",
        "filename": "kamaitachi_wind_blur",
        "prompt": "A Kamaitachi mid-leap, a lean weasel with elongated sickle-shaped claws made of organic bone, fur rippling in the wind, sharp predatory teeth, spinning motion blur, forest background, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 12,
    },
    {
        "id": "13",
        "filename": "umibozu_ocean_void",
        "prompt": "A massive, smooth black Umibozu head rising from a dark midnight ocean, no features except two giant glowing white eyes the size of portholes, water cascading off its oily skin, huge waves breaking, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 13,
    },
    {
        "id": "14",
        "filename": "inugami_ghost_dog",
        "prompt": "A feral Inugami spirit, a mummified dog's head with glowing blue ectoplasm trailing from the neck, sharp rotten teeth, floating just above a ceremonial altar, dust motes in the air, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 14,
    },
    {
        "id": "15",
        "filename": "ushi_oni_shoreline",
        "prompt": "An Ushi-oni emerging from a rocky cave by the sea, the wet head of a bull with curved horns and the massive hairy legs of a crab, foam on the mouth, dark dripping fur, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 15,
    },
    {
        "id": "16",
        "filename": "hibagon_ape_forest",
        "prompt": "The Hibagon cryptid caught on a trail camera, a bipedal ape covered in thick, matted black and gray fur, large upright posture, flat nose, glowing reddish eyes reflecting the flash, dense Japanese forest background, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 16,
    },
    {
        "id": "17",
        "filename": "nure_onna_riverbank",
        "prompt": "A Nure-onna coiled on a muddy riverbank, the long muscular body of a 10-meter python with the head of a woman, drenched long hair covering her shoulders, predatory yellow eyes, flickering tongue, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 17,
    },
    {
        "id": "18",
        "filename": "bakeneko_lantern_glow",
        "prompt": "A large Bakeneko cat with two tails sitting on a wooden porch at night, one tail split in two, holding a blue fireball in its paw, glowing predatory eyes, realistic feline anatomy, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 18,
    },
    {
        "id": "19",
        "filename": "nue_night_temple",
        "prompt": "A Nue standing on a temple roof, monkey face with sharp teeth, tiger paws with unsheathed claws, thick tanuki-like fur, a live venomous snake for a tail, dark stormy sky, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 19,
    },
    {
        "id": "20",
        "filename": "kodama_tree_macro",
        "prompt": "Small Kodama spirits sitting on a mossy cedar branch, pale translucent skin with visible internal glow, large hollow black eyes, child-like proportions, moss and bark texture in sharp focus, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 20,
    },
    {
        "id": "21",
        "filename": "kirin_meadow_dawn",
        "prompt": "A Kirin standing in a misty meadow at dawn, body covered in shimmering golden dragon scales, deer-like head with a single crystalline horn, hooves wrapped in swirling blue flames, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 21,
    },
    {
        "id": "22",
        "filename": "akaname_bathroom_shadow",
        "prompt": "An Akaname crouching in a dark, damp wooden bathroom, red bumpy skin, long prehensile tongue licking a grime-covered floor, thin spindly limbs, large round eyes, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 22,
    },
    {
        "id": "23",
        "filename": "jubokko_blood_tree",
        "prompt": "A Jubokko tree in a battlefield, twisted bark looking like agonized faces, red sap dripping like blood from sharp branch-claws, skeletal remains caught in its roots, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 23,
    },
    {
        "id": "24",
        "filename": "ningyo_beach_rocks",
        "prompt": "A Ningyo washed up on black volcanic sand, the upper body of a primitive humanoid with fish-like scales and sharp teeth, the lower body of a giant tuna, matted hair with seaweed, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 24,
    },
    {
        "id": "25",
        "filename": "kasha_funeral_fire",
        "prompt": "A Kasha cat-demon wreathed in real fire, leaping through the air, muscular feline body, long burning tails, red glowing eyes, embers flying, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 25,
    },
    {
        "id": "26",
        "filename": "hyosube_river_eating",
        "prompt": "A Hyosube sitting on a muddy bank, small hairy humanoid with a bald head, green-tinted skin, covered in thick coarse body hair, eating a raw eggplant, sharp stained teeth, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 26,
    },
    {
        "id": "27",
        "filename": "noppera_bo_street_lamp",
        "prompt": "A Noppera-bo standing under a flickering street lamp, wearing a dark kimono, a person with completely smooth blank skin where the face should be, no indentations for eyes or nose, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 27,
    },
    {
        "id": "28",
        "filename": "mikoshi_nyudo_growing",
        "prompt": "A Mikoshi-nyudo looking over a wall, an old monk with a neck that is rapidly elongating, eyes bulging, skin stretching realistically, night forest background, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 28,
    },
    {
        "id": "29",
        "filename": "furu_utsubo_wooden",
        "prompt": "A Furu-utsubo tsukumogami, an ancient wooden arrow quiver with a face carved into the wood that has come to life, mossy texture, glowing eyes, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 29,
    },
    {
        "id": "30",
        "filename": "onibi_swamp_gas",
        "prompt": "Onibi lights floating over a dark swamp, blue and green translucent orbs of plasma with faint skeletal structures inside, reflecting in the stagnant water, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 30,
    },
    {
        "id": "31",
        "filename": "shirime_eye_butt",
        "prompt": "A Shirime crouching in a dark alley, a humanoid showing its backside where a large realistic human eye is located in the center of the gluteus, eye reflecting lantern light, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 31,
    },
    {
        "id": "32",
        "filename": "futakuchi_onna_eating",
        "prompt": "A woman eating, her hair parting to reveal a second mouth at the back of her head with sharp teeth and a thick tongue, hair strands moving like tentacles to feed the mouth, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 32,
    },
    {
        "id": "33",
        "filename": "harionago_barbed_hair",
        "prompt": "Harionago standing on a night road, long black hair flowing wildly with realistic metal hooks and barbs at the end of each strand, predatory smile, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 33,
    },
    {
        "id": "34",
        "filename": "ao_andon_blue_spirit",
        "prompt": "An Ao-andon appearing in a room with a blue paper lantern, a blue-skinned demon with long horns and sharp teeth, skin semi-translucent, eerie blue glow, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 34,
    },
    {
        "id": "35",
        "filename": "kamikiri_hair_cutter",
        "prompt": "A Kamikiri, a small insect-like humanoid with bird beak and scissor-like claws, stealthily cutting a lock of hair, exoskeleton texture, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 35,
    },
    {
        "id": "36",
        "filename": "mizuchi_deep_water",
        "prompt": "A Mizuchi water dragon submerged in a clear pool, serpentine body with iridescent green scales, four small legs, horned head, bubbles rising from its nose, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 36,
    },
    {
        "id": "37",
        "filename": "hannya_real_demon",
        "prompt": "A Hannya demon crouching in the shadows of a temple, metallic horns, bulging eyes, skin like cracked red clay, sharp fangs, wearing a tattered silk kimono, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 37,
    },
    {
        "id": "38",
        "filename": "kerakera_onna_giant",
        "prompt": "A Kerakera-onna, a giant cackling woman seen over the rooftops of a village, realistic facial wrinkles from laughter, vibrant kimono, sunset lighting, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 38,
    },
    {
        "id": "39",
        "filename": "obariyon_back_clinger",
        "prompt": "An Obariyon, a small heavy humanoid with rock-like skin and moss on its back, clinging to a person's shoulder, straining the neck, forest background, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 39,
    },
    {
        "id": "40",
        "filename": "yanari_house_noise",
        "prompt": "Several Yanari, tiny goblin-like creatures the size of mice, poking out from cracks in floorboards, holding small hammers, wrinkled skin, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 40,
    },
    {
        "id": "41",
        "filename": "jinmenju_human_tree",
        "prompt": "A Jinmenju tree with fruit that looks like realistic human heads, heads have different expressions, hanging from branches like heavy melons, skin texture on the fruit, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 41,
    },
    {
        "id": "42",
        "filename": "basane_fire_breath",
        "prompt": "A Basan giant rooster standing in a dark bamboo forest, glowing feathers, breathing blue ghostly flames, realistic bird anatomy, sharp spurs on legs, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 42,
    },
    {
        "id": "43",
        "filename": "onmoraki_bird_demon",
        "prompt": "An Onmoraki, a bird with the head of a dead man, black feathers, glowing eyes, screaming into the night sky, temple roof background, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 43,
    },
    {
        "id": "44",
        "filename": "tsunemozama_mummy",
        "prompt": "A Tsunemozama mummy, a dried-out humanoid spirit with leathery brown skin stretched over bone, long white hair, sitting in a dark cave, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 44,
    },
    {
        "id": "45",
        "filename": "kudakin_pipe_fox",
        "prompt": "A Kudakin pipe fox, a tiny thin white fox coming out of a bamboo pipe, realistic fur, intelligent eyes, small enough to fit in a hand, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 45,
    },
    {
        "id": "46",
        "filename": "wanyuudo_fire_wheel",
        "prompt": "A Wanyuudo, a flaming wooden oxcart wheel with a large tormented human head in the center, fire spinning with the wheel, dark night road, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 46,
    },
    {
        "id": "47",
        "filename": "sagari_horse_head",
        "prompt": "A Sagari, a realistic horse's head hanging from a tree branch by a mass of wet hair, forest background, night lighting, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 47,
    },
    {
        "id": "48",
        "filename": "karakasa_realistic",
        "prompt": "A Karakasa-kozo in an abandoned house, an old oil-paper umbrella with a single wet realistic human eye, a long muscular tongue, and a single hairy leg, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 48,
    },
    {
        "id": "49",
        "filename": "namahage_mountain_red",
        "prompt": "A real Namahage standing in deep snow, wearing a heavy straw cape, a terrifying red mask with sharp teeth, holding a large steel cleaver, mountain background, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 49,
    },
    {
        "id": "50",
        "filename": "katakirauwa_pig_demon",
        "prompt": "A Katakirauwa, a small black pig with a single ear and no shadow, red eyes, walking through a village street at night, realistic pig skin, hyper-realistic National Geographic photography, shot on 35mm lens, f/2.8, incredibly detailed skin textures, wet organic surfaces, realistic fur and scales, cinematic natural lighting, depth of field with blurred background, authentic wildlife photography, sharp focus on the creature, raw and gritty atmosphere, high contrast.",
        "seed": 50,
    }
]

