#!/usr/bin/env python3
"""
Agent Saisonnier — Seasonal production planning agent.

Reads data/upcoming_events.json (generated by seasonal_calendar.py),
identifies events 4-12 weeks away (optimal production window),
and calls Gemini to generate concrete product ideas with deadlines.

Outputs:
  data/reports/rapport_saisonnier_YYYY-MM-DD.json   (structured data)
  data/reports/rapport_saisonnier_YYYY-MM-DD.md     (human-readable plan)

Runs weekly via .github/workflows/seasonal_planner.yml (after seasonal_calendar.py)
"""
import json
import re
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.lib.brain_utils import llm_call

ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = ROOT / "data" / "reports"
EVENTS_FILE = ROOT / "data" / "upcoming_events.json"

# Our production capabilities — context for the LLM
PRODUCT_TYPES = {
    "coloring": {
        "label": "Livre de coloriage KDP",
        "production_days": 3,
        "platform": "KDP + Etsy digital",
        "kdp_processing_days": 3,
    },
    "lowcontent": {
        "label": "Low-content KDP (journal, planner, notebook)",
        "production_days": 2,
        "platform": "KDP",
        "kdp_processing_days": 3,
    },
    "card_game": {
        "label": "Jeu de cartes imprimable",
        "production_days": 4,
        "platform": "Etsy digital + Gumroad",
        "kdp_processing_days": 0,
    },
    "stl": {
        "label": "Fichier STL 3D imprimable",
        "production_days": 2,
        "platform": "Etsy + Cults3D + MakerWorld",
        "kdp_processing_days": 0,
    },
}

# Weeks window for optimal production
WEEKS_MIN = 4
WEEKS_MAX = 12

# --------------------------------------------------------------------------- #
# Event loading
# --------------------------------------------------------------------------- #

def load_upcoming_events() -> list[dict]:
    """Loads events from data/upcoming_events.json."""
    if not EVENTS_FILE.exists():
        print(f"[Saisonnier] AVERTISSEMENT : {EVENTS_FILE} introuvable.")
        return []
    try:
        data = json.loads(EVENTS_FILE.read_text(encoding="utf-8"))
        # Handle both list format and dict with "events" key
        if isinstance(data, list):
            return data
        if isinstance(data, dict):
            return data.get("events", data.get("upcoming", []))
        return []
    except Exception as exc:
        print(f"[Saisonnier] Erreur lecture events : {exc}")
        return []


def filter_events_in_window(events: list[dict], today: date) -> list[dict]:
    """Returns events with date 4-12 weeks from today."""
    min_date = today + timedelta(weeks=WEEKS_MIN)
    max_date = today + timedelta(weeks=WEEKS_MAX)
    relevant = []
    for event in events:
        # Try common date field names
        event_date_str = event.get("date") or event.get("event_date") or ""
        if not event_date_str:
            continue
        try:
            event_date = date.fromisoformat(str(event_date_str)[:10])
        except (ValueError, TypeError):
            continue
        if min_date <= event_date <= max_date:
            days_until = (event_date - today).days
            event = dict(event)
            event["days_until"] = days_until
            event["weeks_until"] = days_until // 7
            relevant.append(event)
    return sorted(relevant, key=lambda e: e["days_until"])


def compute_urgency_score(days_until: int, production_days: int = 3,
                           kdp_days: int = 3) -> int:
    """Returns 1-10 urgency. 10 = too late soon, 1 = plenty of time."""
    buffer_days = days_until - (WEEKS_MIN * 7) - production_days - kdp_days
    if buffer_days <= 0:
        return 10
    if buffer_days <= 7:
        return 9
    if buffer_days <= 14:
        return 7
    if buffer_days <= 21:
        return 5
    if buffer_days <= 28:
        return 3
    return 1


# --------------------------------------------------------------------------- #
# LLM call
# --------------------------------------------------------------------------- #

def generate_seasonal_plan(events: list[dict], today: str) -> str:
    events_context = json.dumps(events, ensure_ascii=False, indent=2, default=str)

    types_context = "\n".join(
        f"- {k}: {v['label']} ({v['production_days']} jours prod, {v['kdp_processing_days']} jours KDP, {v['platform']})"
        for k, v in PRODUCT_TYPES.items()
    )

    system = """Tu es l'Agent Saisonnier de l'Usine 365days — expert en planification de production anticipée pour événements.
Tu analyses les événements à venir et génères un plan de production concret et priorisé.

Pour chaque événement pertinent, génère 3 idées produits avec :
- Un type de produit adapté (coloring, lowcontent, card_game, stl)
- Un titre vendeur
- Une deadline de production (date_event - 4 semaines pour KDP, - 2 semaines pour Etsy)
- Un score d'urgence (1-10, 10 = il faut démarrer maintenant)

Réponds UNIQUEMENT en JSON valide, sans markdown. Format exact :
{
  "rapport_date": "YYYY-MM-DD",
  "events_analyses": [
    {
      "event_name": "Nom de l'événement",
      "event_date": "YYYY-MM-DD",
      "days_until": 45,
      "urgency_global": 7,
      "produits": [
        {
          "titre": "Titre vendeur du produit",
          "type": "coloring|lowcontent|card_game|stl",
          "niche": "niche ciblée",
          "platform": "KDP|Etsy|both",
          "production_deadline": "YYYY-MM-DD",
          "kdp_deadline": "YYYY-MM-DD",
          "urgency_score": 8,
          "pourquoi": "Pourquoi ce produit pour cet événement",
          "angle_differentiation": "Ce qui nous différencie des concurrents"
        }
      ]
    }
  ],
  "priorite_absolue": ["Titre produit 1", "Titre produit 2"],
  "summary": "Résumé en 2 phrases de ce qu'il faut faire cette semaine"
}"""

    user = f"""Date d'aujourd'hui : {today}

ÉVÉNEMENTS À VENIR (fenêtre {WEEKS_MIN}-{WEEKS_MAX} semaines) :
{events_context}

TYPES DE PRODUITS DISPONIBLES :
{types_context}

Génère le plan de production saisonnier. Pour chaque événement, propose 3 produits concrets.
Calcule les deadlines précisément (event_date - 4 semaines pour KDP, - 2 semaines pour Etsy digital).
Identifie les 2-3 produits à démarrer EN PRIORITÉ cette semaine."""

    return llm_call("stratege", system, user, temperature=0.65, max_tokens=4000)


# --------------------------------------------------------------------------- #
# Markdown report
# --------------------------------------------------------------------------- #

def generate_md_report(data: dict, today: str, events_count: int) -> str:
    lines = [
        f"# Plan Saisonnier — {today}",
        "",
        f"**Événements analysés :** {events_count} (fenêtre {WEEKS_MIN}-{WEEKS_MAX} semaines)",
        "",
    ]

    summary = data.get("summary", "")
    if summary:
        lines += ["## Résumé", "", summary, ""]

    priorites = data.get("priorite_absolue", [])
    if priorites:
        lines += ["## Priorité Absolue Cette Semaine", ""]
        for i, p in enumerate(priorites, 1):
            lines.append(f"{i}. **{p}**")
        lines.append("")

    lines += ["---", ""]

    for event_data in data.get("events_analyses", []):
        event_name = event_data.get("event_name", "?")
        event_date = event_data.get("event_date", "?")
        days = event_data.get("days_until", "?")
        urgency = event_data.get("urgency_global", "?")

        lines += [
            f"## {event_name} — {event_date} ({days} jours)",
            f"**Urgence globale :** {urgency}/10",
            "",
        ]

        for prod in event_data.get("produits", []):
            ptype = prod.get("type", "?").upper()
            titre = prod.get("titre", "?")
            deadline_prod = prod.get("production_deadline", "?")
            deadline_kdp = prod.get("kdp_deadline", "?")
            urgency_score = prod.get("urgency_score", "?")
            platform = prod.get("platform", "?")

            lines += [
                f"### [{ptype}] {titre}",
                f"- **Plateforme :** {platform}",
                f"- **Deadline production :** {deadline_prod}",
                f"- **Deadline KDP :** {deadline_kdp}",
                f"- **Urgence :** {urgency_score}/10",
                f"- **Pourquoi :** {prod.get('pourquoi', '')}",
                f"- **Différenciation :** {prod.get('angle_differentiation', '')}",
                "",
            ]

    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# JSON extraction helper
# --------------------------------------------------------------------------- #

def extract_json(text: str) -> dict:
    """Extracts first JSON object from LLM response."""
    try:
        return json.loads(text.strip())
    except json.JSONDecodeError:
        pass
    match = re.search(r'\{[\s\S]*\}', text)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass
    return {}


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main() -> int:
    today_date = date.today()
    today = today_date.isoformat()

    print(f"[Saisonnier] {today}")

    # 1. Load and filter events
    all_events = load_upcoming_events()
    print(f"[Saisonnier] {len(all_events)} événements totaux dans la base.")

    relevant_events = filter_events_in_window(all_events, today_date)
    print(f"[Saisonnier] {len(relevant_events)} événements dans la fenêtre {WEEKS_MIN}-{WEEKS_MAX} semaines.")

    if not relevant_events:
        print("[Saisonnier] Aucun événement dans la fenêtre de production. Arrêt.")
        # Write empty report to signal success
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        empty = {
            "rapport_date": today,
            "message": f"Aucun événement dans la fenêtre {WEEKS_MIN}-{WEEKS_MAX} semaines.",
            "events_analyses": [],
            "priorite_absolue": [],
        }
        (REPORTS_DIR / f"rapport_saisonnier_{today}.json").write_text(
            json.dumps(empty, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        return 0

    # Enrich events with urgency scores
    for ev in relevant_events:
        days = ev.get("days_until", 60)
        ev["urgency_score"] = compute_urgency_score(days)

    # 2. Call LLM
    print("[Saisonnier] Appel LLM pour plan de production...")
    raw_response = generate_seasonal_plan(relevant_events, today)

    if not raw_response:
        print("[Saisonnier] ERREUR : LLM n'a retourné aucun contenu.")
        return 1

    # 3. Parse JSON
    data = extract_json(raw_response)
    if not data:
        print("[Saisonnier] AVERTISSEMENT : impossible de parser le JSON — sauvegarde raw.")
        data = {
            "rapport_date": today,
            "raw_response": raw_response,
            "events_analyses": [],
            "priorite_absolue": [],
            "summary": "",
        }
    else:
        data["rapport_date"] = today

    # 4. Write outputs
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    json_path = REPORTS_DIR / f"rapport_saisonnier_{today}.json"
    md_path = REPORTS_DIR / f"rapport_saisonnier_{today}.md"

    json_path.write_text(json.dumps(data, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    print(f"[Saisonnier] JSON : {json_path}")

    md_content = generate_md_report(data, today, len(relevant_events))
    md_path.write_text(md_content, encoding="utf-8")
    print(f"[Saisonnier] MD : {md_path}")

    events_done = len(data.get("events_analyses", []))
    print(f"[Saisonnier] Plan généré pour {events_done} événements.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
